const BADGE_FILENAME_MAP: Record<string, string> = {
  S1: 'S1-three-day-streak.png',
  S2: 'S2-week-warrior.png',
  S3: 'S3-fortnight-focus.png',
  S4: 'S4-iron-will.png',
  S5: 'S5-century-legend.png',
  S6: 'S6-hundred-days.png',
  S7: 'S7-early-bird.png',
  S8: 'S8-night-owl.png',
  S9: 'S9-weekend-warrior.png',
  S10: 'S10-year-one.png',
  F1: 'F1-first-melon.png',
  F2: 'F2-focus-rookie.png',
  F3: 'F3-focus-pro.png',
  F4: 'F4-focus-master.png',
  F5: 'F5-focus-legend.png',
  F6: 'F6-time-lord.png',
  F7: 'F7-deep-dive.png',
  F8: 'F8-marathon-runner.png',
  F9: 'F9-ten-a-day.png',
  F10: 'F10-project-pro.png',
  H1: 'H1-first-harvest.png',
  H2: 'H2-full-garden.png',
  H3: 'H3-golden-arrival.png',
  H4: 'H4-golden-collector.png',
  H5: 'H5-warehouse-tycoon.png',
  H6: 'H6-first-synthesis.png',
  H7: 'H7-synthesis-master.png',
  H8: 'H8-first-slice.png',
  H9: 'H9-hundred-slices.png',
  H10: 'H10-tool-collector.png',
  G1: 'G1-first-planting.png',
  G2: 'G2-first-farm-harvest.png',
  G3: 'G3-hundred-plants.png',
  G4: 'G4-galaxy-conqueror.png',
  G5: 'G5-codex-master.png',
  G6: 'G6-alien-friend.png',
  G7: 'G7-thief-buster.png',
  G8: 'G8-evergreen-farm.png',
  X1: 'X1-time-traveler.png',
  X2: 'X2-valentine-melon.png',
  X3: 'X3-sound-explorer.png',
  X4: 'X4-perfectionist.png',
  X5: 'X5-all-rounder.png',
  X6: 'X6-midnight-gardener.png',
};

export function getBadgeUrl(id: string): string {
  const filename = BADGE_FILENAME_MAP[id];
  return filename ? `/badges/${filename}` : '';
}
